import { describe, it, expect } from '@jest/globals';
import puppeteer from 'puppeteer';
import http from 'http';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { validateVsdx } from '../src/validate';

// Real end-to-end smoke test for the fully-client-side browser build. Boots
// a tiny local file server, loads the bundled app in Puppeteer, drives the
// UI to convert a small flowchart, and pulls the generated bytes back out
// via page.evaluate so we can run validateVsdx on them.
//
// Skipped when `dist/browser/app.js` isn't built (run `npm run build:browser`
// first). This is intentional — the bundle is a separate target, and we want
// `npm test` to stay fast.

const here = path.dirname(fileURLToPath(import.meta.url));
const bundlePath = path.resolve(here, '..', 'dist', 'browser', 'app.js');
const htmlPath = path.resolve(here, '..', 'dist', 'browser', 'index.html');
const ready = fs.existsSync(bundlePath) && fs.existsSync(htmlPath);
const describeIfBuilt = ready ? describe : describe.skip;

describeIfBuilt('browser bundle (client-side flow)', () => {
    it('renders + extracts + generates a valid VSDX entirely in the browser', async () => {
        const dir = path.dirname(bundlePath);

        // Tiny static file server over the dist/browser directory.
        const serverLog: string[] = [];
        const server = http.createServer((req, res) => {
            const rel = (req.url || '/').split('?')[0];
            // Favicon stub: every browser asks for /favicon.ico; answer with
            // an empty 204 so the page console stays clean.
            if (rel === '/favicon.ico') { res.writeHead(204).end(); return; }
            const target = rel === '/' ? 'index.html' : rel.replace(/^\/+/, '');
            const abs = path.resolve(dir, target);
            if (!abs.startsWith(dir + path.sep) && abs !== dir) {
                serverLog.push(`403 ${rel}`); res.writeHead(403).end(); return;
            }
            fs.readFile(abs, (err, buf) => {
                if (err) { serverLog.push(`404 ${rel} -> ${abs}`); res.writeHead(404).end(); return; }
                serverLog.push(`200 ${rel} (${buf.length} bytes)`);
                const ext = path.extname(abs).toLowerCase();
                const type = ext === '.html' ? 'text/html'
                    : ext === '.js' ? 'application/javascript'
                    : 'application/octet-stream';
                res.writeHead(200, { 'Content-Type': type }).end(buf);
            });
        });
        await new Promise<void>(r => server.listen(0, '127.0.0.1', r));
        const port = (server.address() as any).port;

        const browser = await puppeteer.launch({
            headless: true,
            args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage'],
        });
        try {
            const page = await browser.newPage();
            const errors: string[] = [];
            page.on('pageerror', e => errors.push(`pageerror: ${e.message}`));
            page.on('console', m => {
                // /favicon.ico 404s are a browser default and noise.
                if (m.type() !== 'error') return;
                const t = m.text();
                if (/favicon\.ico/.test(t)) return;
                errors.push(`console.error: ${t}`);
            });
            page.on('response', r => {
                if (r.status() >= 400 && !/favicon/.test(r.url())) {
                    errors.push(`HTTP ${r.status()} ${r.url()}`);
                }
            });

            await page.goto(`http://127.0.0.1:${port}/`, { waitUntil: 'networkidle0' });

            // Intercept the auto-download by overriding the URL.createObjectURL
            // -> link click pipeline: stash the Blob bytes on window for retrieval.
            await page.evaluate(() => {
                (window as any).__vsdxBytes = null;
                const origCreate = URL.createObjectURL.bind(URL);
                URL.createObjectURL = (b: any) => {
                    if (b instanceof Blob) {
                        b.arrayBuffer().then(buf => {
                            (window as any).__vsdxBytes = new Uint8Array(buf);
                        });
                    }
                    return origCreate(b);
                };
                // Prevent the synthetic click from actually navigating.
                const origAppend = HTMLBodyElement.prototype.appendChild;
                (HTMLBodyElement.prototype as any).appendChild = function (this: any, n: any) {
                    if (n?.tagName === 'A' && n.download) {
                        n.click = () => {};
                    }
                    return origAppend.call(this, n);
                };
            });

            // Drive the UI: set source, click Convert, wait for terminal status.
            await page.evaluate(() => {
                const t = document.getElementById('src') as HTMLTextAreaElement;
                t.value = 'flowchart TD\n A[Start] --> B{Q}\n B -->|yes| C[OK]\n B -->|no| D[Stop]';
            });
            await page.click('#convert');
            await page.waitForFunction(
                () => /^(Done|Generated)/.test(document.getElementById('status')?.textContent || ''),
                { timeout: 30_000 },
            );

            // Pull the captured bytes out.
            const bytes: number[] = await page.evaluate(async () => {
                const start = Date.now();
                while (!(window as any).__vsdxBytes && Date.now() - start < 5_000) {
                    await new Promise(r => setTimeout(r, 50));
                }
                const u8 = (window as any).__vsdxBytes as Uint8Array | null;
                return u8 ? Array.from(u8) : [];
            });

            if (errors.length) console.error('PAGE ERRORS:', errors);
            if (errors.length) console.error('SERVER LOG:', serverLog);
            expect(errors).toEqual([]);
            expect(bytes.length).toBeGreaterThan(2_000);
            // PK signature for ZIP / VSDX.
            expect(bytes[0]).toBe(0x50);
            expect(bytes[1]).toBe(0x4b);

            // Round-trip through the validator to confirm the package is structurally sound.
            const u8 = new Uint8Array(bytes);
            const result = await validateVsdx(u8);
            if (!result.ok) throw new Error('validator: ' + result.errors.join('; '));
            expect(result.ok).toBe(true);
        } finally {
            await browser.close();
            await new Promise<void>(r => server.close(() => r()));
        }
    }, 90_000);
});
